version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
    groups:
      bun-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:45"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
    groups:
      actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
